---
platform: linux
image_resource:
  type: docker-image
  source: {repository: jrjohnsongoog/omgci}
inputs:
- name: omg-src-in
- name: omg-env
outputs:
- name: omg-env
run:
  path: omg-src-in/ci/tasks/create-infrastructure.sh
